theme = "monokai"

[editor]
line-number = "absolute"
mouse = false
color-modes = true
scroll-lines = 0

[editor.file-picker]
hidden = false

# [editor.lsp]
# display-inlay-hints = true

[keys.insert]
# Esc is both far away from common keys and it is lagging on my laptop.
"C-n"  = "normal_mode"

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it
 